# Generated by Django 5.1.1 on 2024-10-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='age_end',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='group',
            name='age_start',
            field=models.IntegerField(default=6),
        ),
    ]
