# Generated by Django 5.1.1 on 2024-10-20 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_alter_callbackrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callbackrequest',
            options={'ordering': ['-time_create', 'full_name'], 'verbose_name': 'Заявки на звонок для уточнения', 'verbose_name_plural': 'Заявки на звонок для уточнения'},
        ),
        migrations.AlterModelOptions(
            name='triallesson',
            options={'ordering': ['-time_create', 'direction'], 'verbose_name': 'Заявки на тренировку', 'verbose_name_plural': 'Заявки на тренировки'},
        ),
        migrations.AlterField(
            model_name='news',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='club.news', verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.group', verbose_name='Группа'),
        ),
    ]
