# Generated by Django 5.1.1 on 2024-10-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_alter_photo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='triallesson',
            options={'ordering': ['-time_create', 'sport'], 'verbose_name': 'Заявки на тренировку', 'verbose_name_plural': 'Заявки на тренировки'},
        ),
        migrations.RemoveField(
            model_name='triallesson',
            name='direction',
        ),
        migrations.AddField(
            model_name='group',
            name='kind_of_sport',
            field=models.CharField(default='Самбо', max_length=100, verbose_name='Название спорта'),
        ),
        migrations.AddField(
            model_name='triallesson',
            name='sport',
            field=models.CharField(default='Самбо', max_length=100, verbose_name='Вид спорта'),
        ),
    ]
