# Generated by Django 5.1.1 on 2024-10-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_alter_group_kind_of_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='kind_of_sport',
            field=models.CharField(choices=[('Sambo', 'Самбо'), ('Karate', 'Карате'), ('Taekwondo', 'Тхэквондо')], default='Sambo', max_length=100, verbose_name='Название спорта'),
        ),
    ]
