# Generated by Django 5.1.1 on 2024-10-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0010_alter_group_kind_of_sport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'ordering': ['ordering', 'fio'], 'verbose_name': 'Тренер', 'verbose_name_plural': 'Тренеры'},
        ),
        migrations.AddField(
            model_name='coach',
            name='ordering',
            field=models.IntegerField(default=6, verbose_name='Порядок'),
        ),
    ]
